spring:
  application:
    name: Spring-AI-tutorial
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}

  chatclient:
    tools:
      weather:
        enabled: true
      pirate:
        enabled: false